name: 'Autoroute'
description: 'Autoroute a given DSN file to SES with FreeRouting'
inputs:
  boards:
    description: 'Specctra SES output file'
    required: true
runs:
  using: 'docker'
  image: 'docker://ceoloide/ergogen-freerouting:latest'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      for board in ${{ inputs.boards }};
      do
        echo "Processing $board";
        if [ -e pcbs/${board}.ses ]; then
          echo "Cleaning up pcbs/${board}.ses";
          rm -f pcbs/${board}.ses;
        fi
        if [ -e pcbs/${board}.dsn ]; then
          echo "Autoroute PCB";
          java -jar /opt/freerouting.jar -de pcbs/${board}.dsn -do pcbs/${board}.ses --user-data-path ./freerouting -mp 20 -mt 1 -dct 0 --gui.enabled=false --profile.email=marco.massarelli@gmail.com
        fi
      done